# This is a basic workflow to help you get started with Actions

name: kernel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [6.7-working]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: sudo apt update && sudo apt install build-essential gcc-aarch64-linux-gnu bc flex bison 7zip kmod bash cpio binutils tar git wget dpkg libssl-dev android-tools-mkbootimg

      - name: Build kernel
        run: sudo sh nabu-kernel_build.sh ${{ matrix.version }}

      - name: Generate zImage and boot image
        run: |
          _kernel_version=$(make -C linux kernelrelease -s)
          cat linux-xiaomi-nabu/boot/vmlinuz-$_kernel_version linux-xiaomi-nabu/boot/dtb-$_kernel_version > zImage
          mkbootimg --kernel zImage --cmdline "root=PARTLABEL=linux loglevel=3" --base 0x00000000 --kernel_offset 0x00008000 --tags_offset 0x00000100 --pagesize 4096 --id -o linux.boot.img

      - name: Upload boot image
        uses: actions/upload-artifact@v4.0.0
        with:
          # Artifact name
          name: linux-boot-image_${{ matrix.version }}
          path: linux.boot.img
