# This is a basic workflow to help you get started with Actions

name: Extract Kernel

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  extract-kernel:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kernel: [6.7-working]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt update && sudo apt install unzip dpkg-dev
      - name: Download pre-built kernel
        run: |
          # 替换为你实际的下载链接，这里假设你将文件上传到了 GitHub Releases
          wget -O xiaomi-nabu-debs_${{ matrix.kernel }}.zip https://github.com/wdgu/ubuntu-xiaomi-nabu/releases/download/rootfs/xiaomi-nabu-debs_${{ matrix.kernel }}.zip
          unzip xiaomi-nabu-debs_${{ matrix.kernel }}.zip
      - name: Extract kernel image from deb package
        run: |
          # 创建临时目录
          mkdir tmp_kernel_extract
          # 解压 linux-xiaomi-nabu.deb 包到临时目录
          dpkg-deb -x linux-xiaomi-nabu.deb tmp_kernel_extract
          # 查找内核镜像文件，通常可能是 vmlinuz 或 Image 之类的
          KERNEL_IMAGE=$(find tmp_kernel_extract -name "vmlinuz*" -o -name "Image*" | head -n 1)
          if [ -z "$KERNEL_IMAGE" ]; then
            echo "Kernel image not found in the deb package."
            exit 1
          fi
          # 将内核镜像复制到工作目录并重命名为 linux.boot.img
          cp "$KERNEL_IMAGE" linux.boot.img
      - name: Upload kernel image
        uses: actions/upload-artifact@v4.0.0
        with:
          name: linux-boot-img_${{ matrix.kernel }}
          path: linux.boot.img
